Use bash shebang for scripts
artilleryio/artillery-operator pull request #29
Opened 2022-04-05 20:23 UTC by juanig1

Handle cases where bash is not the default non-interactive shell (e.g., Debian).

Swapping 'source' for '.' and revisiting [line 5](https://github.com/juanig1/artillery-operator/blob/a8b92de72c081feb34d156ef799f69354d6e712e/hack/kind/kind-with-registry.sh#L5) of hack/kind/kind-with-registry.sh (bad substitution error) may be an option if we want to keep using /bin/sh.

2022-04-05 20:23 UTC, juanig1 commented
This is a workaround for my system; but may be the wrong approach. Feedback is appreciated!

2022-04-07 11:43 UTC, ezodude requested changes
All in all makes sense. 👍 

Can we update the `goreleaser` [Makefile task](https://github.com/artilleryio/artillery-operator/blob/main/Makefile#L260) to work like the other commands using go install, i.e. Kustomize, etc.. (it already does that but we no longer need the `go-get-install` function)

We'll need to revisit this once the latest Kubebuilder/Operator-SDK is released.

2022-04-07 14:17 UTC, ezodude approved these changes
LGTM 💯

2022-04-08 08:43 UTC, ezodude approved these changes
👍 lgtm

2022-04-08 08:43 UTC, ezodude commented on hack/prom-pushgateway/up.sh
> +unzip "${kube_prom_zip}" -d "${script_dir}"
Turns out on a Mac, `tar` symlinks to `bsdtar` not GNU tar. There are some minor differences there, so we're definitely not using the same tar.

`unzip` is a good replacement. 👍

2022-04-08 08:44 UTC, merged